import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { Toaster } from "@/components/ui/toaster";

import 'maplibre-gl/dist/maplibre-gl.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
				<body className="grid grid-rows-[min-content,min-content,auto] w-screen h-screen p-12">


					<header className="flex items-center w-full justify-between">
						<h1 className="text-2xl font-semibold">
							live<span className="text-yellow-400">bus</span>
						</h1>
						<Select>
							<SelectTrigger className="w-[180px]">
								<SelectValue placeholder="Companhia" />
							</SelectTrigger>
							<SelectContent>
								<SelectItem value="light">Livebus inc.</SelectItem>
								<SelectItem value="dark">Dark</SelectItem>
								<SelectItem value="system">System</SelectItem>
							</SelectContent>
						</Select>
					</header>
					<Separator className="my-4" orientation="horizontal" />
					{children}




					{/* <div className="p-8 h-screen flex flex-col">
						<header className="flex items-center w-full justify-between">
							<h1 className="text-2xl font-semibold">
								live<span className="text-yellow-400">bus</span>
							</h1>
							<Select>
								<SelectTrigger className="w-[180px]">
									<SelectValue placeholder="Companhia" />
								</SelectTrigger>
								<SelectContent>
									<SelectItem value="light">Livebus inc.</SelectItem>
									<SelectItem value="dark">Dark</SelectItem>
									<SelectItem value="system">System</SelectItem>
								</SelectContent>
							</Select>
						</header>
						<Separator className="my-8" orientation="horizontal" />
						<main className="h-full">{children}</main>
						<Toaster />
					</div> */}
				</body>
				<Toaster />
			</ThemeProvider>
		</html>
	);
}
